---
  - hosts: all
    become: yes

    tasks:
      - name: install required items
        apt:
          state: present
          name:
          - python3-apt
          - python3-pycurl

      - name:
      
