---
- name: Get software for apt repository management
  apt:
    state: present
    name: 
      - python3-apt
      - python3-pycurl

- name: Add ondrej Repository for later versions of PHP.
  apt_repository: repo='ppa:ondrej/php' update_cache=yes

- name: "Install apache, mysql, PHP and other dependencies"
  apt:
    state: present
    name:
      - acl
      - git
      - curl
      - unzip
      - sendmail
      - apache2
      - php7.4-common
      - php7.4-cli
      - php7.4-dev
      - php7.4-gd
      - php7.4-json
      - php7.4-opcache
      - php7.4-xml
      - php7.4-mbstring
      - php7.4-pdo
      - php7.4-mysql
      - php-apcu
      - libpcre3-dev
      - libapache2-mod-php7.4
      - python3-mysqldb
      - mysql-server

- name: disable firewall for testing
  service: name=ufw state=stopped

- name: "Start Apache, Mysql, PHP"
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - apache2
    - mysql

#config items
- name: Enable Apache rewrite Module (required for drupal)
  apache2_module: name=rewrite state=present
  notify: restart Apache2

- name: Add Apache virtualhost for drupal.
  template: 
    src: "templates/drupal.test.conf.j2"
    dest: "/etc/apache2/sites-available/{{ domain }}.test.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart Apache2

- name: Enable the drupal site
  command: >
    a2ensite {{ domain }}.test
    creates=/etc/apache2/sites-enabled/{{ domain }}.test.conf
  notify: restart Apache2

- name: Disable the default site.
  command: > 
    a2dissite 000-default
    removes=/etc/apache2/sites-enabled/000-default.conf
  notify: restart Apache2
