---
- name: Create Mysql DB for Drupal.
  mysql_db: "db={{ domain }} state=present"

- name: Create mysql user for drupal
  mysql_user:
    name: "{{ domain }}"
    password: "1234"
    priv: "{{ domain }}.*:ALL"
    host: localhost
    state: present
