---
- name: create the VM
  community.general.proxmox_kvm:
    api_host: odin.jplace.lan
    node: odin
    api_user: '{{ api_username }}'
    api_password: '{{ api_passwd }}'
    name: '{{ vm_name }}'
    clone: Midgard
    vmid: 9009
    newid: '{{ vmid }}'
    timeout: 3600

- name: update the vm with the new info
  community.general.proxmox_kvm:
    api_host: odin.jplace.lan
    node: odin
    api_user: '{{ api_username }}'
    api_password: '{{ api_passwd }}'
    name: '{{ vm_name }}'
    memory: 4096
    cores: 4
    net:
      net0: 'virtio,bridge=vmbr0'
    nameservers:
      - '192.168.0.14'
      - '192.168.0.1'
    ipconfig:
      ipconfig0: 'ip=192.168.0.56/24,gw=192.168.0.1'
    update: yes

- name: authentication
  ansible.builtin.uri:
    url: "https://odin.jplace.lan:8006/api2/json/access/ticket"
    method: POST
    body_format: form-urlencoded
    body:
      username: '{{ api_username }}'
      password: '{{ api_passwd }}'
    validate_certs: no
  register: auth

- name: resize disk
  ansible.builtin.uri:
    url: "https://odin.jplace.lan:8006/api2/json/nodes/odin/qemu/{{ vmid }}/resize"
    method: PUT
    headers: 
      Cookie: "PVEAuthCookie={{ auth.json.data.ticket }}"
      CSRFPreventionToken: "{{ auth.json.data.CSRFPreventionToken }}"
    body_format: form-urlencoded
    body:
      disk: scsi0
      size: "{{ hd_size }}G"
    validate_certs: no

- name: Startup the Created VM
  community.general.proxmox_kvm:
    api_host: odin.jplace.lan
    node: odin
    api_user: '{{ api_username }}'
    api_password: '{{ api_passwd }}'
    name: '{{ vm_name }}'
    state: started